-- ============================================
-- V005__genetics.sql
-- Flyway Migration: Genetics Module
-- Tables: genetic_sample, genetic_variant,
--         genetic_variant_annotation, genetic_polygenic_score,
--         genetic_sample_qc
-- ============================================

-- ============================================
-- 1. genetic_sample — sample collection & processing
-- ============================================
CREATE TABLE IF NOT EXISTS genetic_sample (
    id                          BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
    sample_code                 VARCHAR(64)     NOT NULL            COMMENT 'Unique human-readable sample identifier',
    subject_id                  BIGINT UNSIGNED NOT NULL            COMMENT 'FK → subject.id — research subject',
    family_id                   VARCHAR(64)                         COMMENT 'Family/pedigree identifier for trio studies',
    paternal_id                 VARCHAR(64)                         COMMENT 'Paternal sample code for pedigree',
    maternal_id                 VARCHAR(64)                         COMMENT 'Maternal sample code for pedigree',
    sex                         VARCHAR(8)                          COMMENT 'Genetically determined sex (GB/T 2261.1): 0-unknown,1-male,2-female,9-unspecified',
    is_affected                 TINYINT(1)      DEFAULT 0           COMMENT 'Affection status for case/control studies (0=control,1=case)',
    sample_type                 VARCHAR(32)     NOT NULL DEFAULT 'blood' COMMENT 'Sample type: blood,saliva,buccal_swab,csf,tissue,dna_extract,rna_extract',
    source_type                 VARCHAR(32)                         COMMENT 'Source: peripheral_blood,cord_blood,csf,brain_tissue,saliva,buccal,other',
    tissue_type                 VARCHAR(64)                         COMMENT 'Tissue type when source is tissue (e.g. frontal_cortex,hippocampus)',
    collection_date             DATE                                COMMENT 'Date of sample collection (YYYY-MM-DD)',
    collection_time             DATETIME                            COMMENT 'Exact datetime of sample collection',
    collection_site             VARCHAR(128)                        COMMENT 'Collection institution name / hospital',
    collection_method           VARCHAR(64)                         COMMENT 'Collection protocol/method reference',
    collector_name              VARCHAR(64)                         COMMENT 'Name of person who performed collection',
    sample_volume               DECIMAL(10,4)                       COMMENT 'Collected sample volume',
    sample_volume_unit          VARCHAR(16)     DEFAULT 'ml'        COMMENT 'Volume unit: ml,μL',
    concentration               DECIMAL(10,4)                       COMMENT 'DNA/RNA concentration (ng/μL)',
    concentration_unit          VARCHAR(16)     DEFAULT 'ng/μL'     COMMENT 'Concentration unit',
    total_yield_ng              DECIMAL(12,2)                       COMMENT 'Total nucleic acid yield in nanograms',
    od260_280                   DECIMAL(6,3)                        COMMENT 'A260/A280 ratio — protein/phenol contamination indicator',
    od260_230                   DECIMAL(6,3)                        COMMENT 'A260/A230 ratio — salt/organic contamination indicator',
    rin                         DECIMAL(5,2)                        COMMENT 'RNA Integrity Number (1-10)',
    din                         DECIMAL(5,2)                        COMMENT 'DNA Integrity Number (1-10)',
    gel_image_path              VARCHAR(512)                        COMMENT 'MinIO path to gel electrophoresis image',
    quality_status              VARCHAR(16)     DEFAULT 'PENDING'   COMMENT 'Quality status: PENDING,PASS,WARN,FAIL',
    quality_metrics             JSON                                COMMENT 'Additional quality metrics as JSON key-value pairs',
    preservation_method         VARCHAR(64)                         COMMENT 'Preservation: frozen,ffpe,edta,paxgene,rnalater,other',
    storage_location            VARCHAR(255)                        COMMENT 'Physical location: freezer/rack/box/position',
    storage_condition           VARCHAR(64)                         COMMENT 'Storage condition: -80C,-20C,4C,room_temp,liquid_nitrogen',
    freeze_thaw_cycles          INT             DEFAULT 0           COMMENT 'Cumulative freeze-thaw cycles',
    extraction_method           VARCHAR(128)                        COMMENT 'DNA/RNA extraction kit/protocol',
    extraction_date             DATE                                COMMENT 'Date of nucleic acid extraction',
    sequencing_platform         VARCHAR(64)                         COMMENT 'Sequencer: Illumina_NovaSeq,Illumina_HiSeq,BGI_DNBSEQ,ONT_PromethION,PacBio_Sequel',
    sequencing_type             VARCHAR(32)                         COMMENT 'WGS,WES,targeted_panel,snp_array,methylation_array,rna_seq,atac_seq',
    library_kit                 VARCHAR(128)                        COMMENT 'Library preparation kit name and version',
    library_method              VARCHAR(64)                         COMMENT 'Library method: PCR,PCR_free,enrichment,other',
    target_regions              VARCHAR(512)                        COMMENT 'Target regions/genes list for targeted/enrichment sequencing',
    target_bed_file             VARCHAR(512)                        COMMENT 'MinIO path to target regions BED file',
    read_length                 INT                                 COMMENT 'Sequencing read length (bp)',
    read_type                   VARCHAR(16)     DEFAULT 'PAIRED'    COMMENT 'PAIRED or SINGLE',
    coverage_target             DECIMAL(7,2)                        COMMENT 'Target mean coverage depth (X)',
    coverage_achieved           DECIMAL(7,2)                        COMMENT 'Achieved mean coverage depth (X)',
    coverage_20x_pct            DECIMAL(5,2)                        COMMENT 'Percentage of target bases covered at >=20x',
    pct_q30                     DECIMAL(5,2)                        COMMENT 'Percentage of bases with Q>=30',
    total_reads                 BIGINT UNSIGNED                     COMMENT 'Total number of reads',
    mapped_reads_pct            DECIMAL(5,2)                        COMMENT 'Percentage of reads mapped to reference',
    duplicate_reads_pct         DECIMAL(5,2)                        COMMENT 'Percentage of duplicate reads',
    fastq_files                 JSON                                COMMENT 'FASTQ file paths in MinIO — JSON array of string paths',
    bam_file_path               VARCHAR(512)                        COMMENT 'Aligned BAM file path in MinIO',
    vcf_file_path               VARCHAR(512)                        COMMENT 'Joint/single-sample VCF file path in MinIO',
    gvcf_file_path              VARCHAR(512)                        COMMENT 'gVCF file path in MinIO',
    cram_file_path              VARCHAR(512)                        COMMENT 'CRAM file path in MinIO',
    cnv_file_path               VARCHAR(512)                        COMMENT 'Copy-number variant calls file path',
    report_file_path            VARCHAR(512)                        COMMENT 'Analysis report PDF/HTML path',
    reference_genome            VARCHAR(32)     DEFAULT 'GRCh38'    COMMENT 'Reference genome: GRCh37,GRCh38,T2T-CHM13',
    reference_build             VARCHAR(32)                         COMMENT 'Detailed build: e.g. GRCh38.p14',
    pipeline_name               VARCHAR(64)                         COMMENT 'Bioinformatics pipeline: GATK_best_practices,DRAGEN,DeepVariant',
    pipeline_version            VARCHAR(32)                         COMMENT 'Pipeline version number',
    pipeline_config             JSON                                COMMENT 'Pipeline configuration parameters as JSON',
    variant_count               INT UNSIGNED                        COMMENT 'Total number of variants called (PASS only)',
    snv_count                   INT UNSIGNED                        COMMENT 'Single-nucleotide variant count',
    indel_count                 INT UNSIGNED                        COMMENT 'Insertion/deletion count',
    cnv_count                   INT UNSIGNED                        COMMENT 'Copy-number variant count',
    sv_count                    INT UNSIGNED                        COMMENT 'Structural variant count (>=50bp)',
    ti_tv_ratio                 DECIMAL(5,3)                        COMMENT 'Transition / Transversion ratio',
    het_hom_ratio               DECIMAL(7,3)                        COMMENT 'Heterozygous / Homozygous variant ratio',
    status                      VARCHAR(32)     NOT NULL DEFAULT 'COLLECTED'
        COMMENT 'Sample lifecycle: COLLECTED,EXTRACTED,QC_CHECK,SEQUENCING,SEQUENCED,ANALYZING,ANALYZED,QC_FAILED,ARCHIVED',
    is_flagged                  TINYINT(1)      DEFAULT 0           COMMENT 'Admin-flagged for review/audit',
    is_deleted                  TINYINT(1)      DEFAULT 0           COMMENT 'Soft-delete marker',
    notes                       TEXT                                COMMENT 'Free-text remarks',
    created_by                  BIGINT UNSIGNED                     COMMENT 'FK → user.id — record creator',
    updated_by                  BIGINT UNSIGNED                     COMMENT 'FK → user.id — last modifier',
    created_at                  DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Record creation timestamp',
    updated_at                  DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Record last update timestamp',
    PRIMARY KEY (id),
    UNIQUE KEY uk_sample_code             (sample_code),
    INDEX idx_subject_id                  (subject_id),
    INDEX idx_family_id                   (family_id),
    INDEX idx_sample_type                 (sample_type),
    INDEX idx_source_type                 (source_type),
    INDEX idx_collection_date             (collection_date),
    INDEX idx_status                      (status),
    INDEX idx_quality_status              (quality_status),
    INDEX idx_sequencing_type             (sequencing_type),
    INDEX idx_sequencing_platform         (sequencing_platform),
    INDEX idx_reference_genome            (reference_genome),
    INDEX idx_created_by                  (created_by),
    INDEX idx_subject_status              (subject_id, status),
    INDEX idx_is_deleted                  (is_deleted),
    CONSTRAINT fk_genetic_sample_subject   FOREIGN KEY (subject_id)  REFERENCES subject(id)   ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_genetic_sample_created   FOREIGN KEY (created_by)  REFERENCES `user`(id)     ON DELETE SET NULL  ON UPDATE CASCADE,
    CONSTRAINT fk_genetic_sample_updated   FOREIGN KEY (updated_by)  REFERENCES `user`(id)     ON DELETE SET NULL  ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='Genetic sample metadata — tracks biospecimens from collection through sequencing and variant calling';


-- ============================================
-- 2. genetic_variant — individual variant records
-- ============================================
CREATE TABLE IF NOT EXISTS genetic_variant (
    id                          BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
    sample_id                   BIGINT UNSIGNED NOT NULL             COMMENT 'FK → genetic_sample.id',
    subject_id                  BIGINT UNSIGNED NOT NULL             COMMENT 'FK → subject.id (denormalised for query performance)',
    chromosome                  VARCHAR(8)      NOT NULL             COMMENT 'Chromosome: 1-22,X,Y,MT (CHR prefix stripped)',
    position                    BIGINT UNSIGNED NOT NULL             COMMENT '1-based genomic position on the chromosome',
    ref_allele                  VARCHAR(512)    NOT NULL             COMMENT 'Reference allele sequence',
    alt_allele                  VARCHAR(512)    NOT NULL             COMMENT 'Alternate allele sequence (comma-separated if multi-allelic)',
    rs_id                       VARCHAR(32)                          COMMENT 'dbSNP rs identifier (e.g. rs429358 for ApoE ε4)',
    variant_id_col              VARCHAR(64)                          COMMENT 'VCF ID column value from original file',
    variant_type                VARCHAR(16)                          COMMENT 'SNV,INS,DEL,MNV,CNV,DUP,INV,BND,COMPLEX',
    genotype                    VARCHAR(16)                          COMMENT 'Genotype call: 0/0,0/1,1/1,0|1,./. etc.',
    genotype_quality            DECIMAL(10,2)                        COMMENT 'Phred-scaled genotype quality (GQ)',
    allele_depth_ref            INT                                  COMMENT 'Read depth for reference allele (AD[0])',
    allele_depth_alt            INT                                  COMMENT 'Read depth for alternate allele (AD[1])',
    read_depth                  INT                                  COMMENT 'Total read depth at the site (DP)',
    allele_frequency            DECIMAL(8,6)                         COMMENT 'Alternate allele frequency (AF) in this sample',
    quality_score               DECIMAL(10,2)                        COMMENT 'Phred-scaled variant quality score (QUAL)',
    filter_status               VARCHAR(64)     DEFAULT 'PASS'       COMMENT 'VCF FILTER column: PASS or semi-colon separated filter names',
    phred_likelihood            JSON                                 COMMENT 'Phred-scaled likelihoods (PL) as JSON array',
    strand_bias                 DECIMAL(10,4)                        COMMENT 'Strand bias (FS / SOR)',
    mapping_quality             DECIMAL(8,2)                         COMMENT 'Root-mean-square mapping quality (MQ)',
    mapping_quality_rank_sum    DECIMAL(10,4)                        COMMENT 'Mann-Whitney rank sum of mapping quality (MQRankSum)',
    read_pos_rank_sum           DECIMAL(10,4)                        COMMENT 'Mann-Whitney rank sum of read position (ReadPosRankSum)',
    inbreeding_coeff            DECIMAL(10,6)                        COMMENT 'Inbreeding coefficient from Hardy-Weinberg (InbreedingCoeff)',
    excess_het                  DECIMAL(10,4)                        COMMENT 'Excess heterozygosity (ExcessHet)',
    base_q_rank_sum             DECIMAL(10,4)                        COMMENT 'Mann-Whitney rank sum of base quality (BaseQRankSum)',
    clipping_rank_sum           DECIMAL(10,4)                        COMMENT 'Mann-Whitney rank sum of clipping (ClippingRankSum)',
    gene_symbol                 VARCHAR(64)                          COMMENT 'HGNC gene symbol (e.g. APOE, APP, PSEN1, MAPT, SNCA)',
    gene_id                     VARCHAR(32)                          COMMENT 'Ensembl gene ID (ENSG...)',
    transcript_id               VARCHAR(32)                          COMMENT 'Ensembl transcript ID (ENST...)',
    consequence                 VARCHAR(128)                         COMMENT 'Sequence Ontology consequence: missense_variant,stop_gained,frameshift_variant,splice_donor_variant,intron_variant,upstream_gene_variant,etc.',
    impact                      VARCHAR(16)                          COMMENT 'Predicted impact: HIGH,MODERATE,LOW,MODIFIER',
    amino_acid_change           VARCHAR(64)                          COMMENT 'HGVS protein notation (e.g. p.Arg176Cys)',
    hgvs_c                      VARCHAR(128)                         COMMENT 'HGVS coding DNA notation',
    hgvs_g                      VARCHAR(128)                         COMMENT 'HGVS genomic notation',
    codon_change                VARCHAR(64)                          COMMENT 'Codon change (e.g. cgc/Tgc)',
    exon_number                 VARCHAR(16)                          COMMENT 'Exon number affected (e.g. 4/17)',
    intron_number               VARCHAR(16)                          COMMENT 'Intron number if intronic',
    biotype                     VARCHAR(32)                          COMMENT 'Transcript biotype: protein_coding,nonsense_mediated_decay,lncRNA',
    sift_score                  DECIMAL(6,4)                         COMMENT 'SIFT prediction score (<0.05 = deleterious)',
    sift_prediction             VARCHAR(24)                          COMMENT 'SIFT: tolerated,tolerated_low_confidence,deleterious,deleterious_low_confidence',
    polyphen2_score             DECIMAL(6,4)                         COMMENT 'PolyPhen-2 HumDiv/HumVar score',
    polyphen2_prediction        VARCHAR(32)                          COMMENT 'PolyPhen-2: benign,possibly_damaging,probably_damaging,unknown',
    cadd_phred                  DECIMAL(8,4)                         COMMENT 'CADD Phred-scaled score (commonly >15 or >20 as pathogenic threshold)',
    cadd_raw                    DECIMAL(10,6)                        COMMENT 'CADD raw score',
    revel_score                 DECIMAL(6,4)                         COMMENT 'REVEL ensemble meta-predictor score for missense variants',
    gerp_rs                     DECIMAL(6,2)                         COMMENT 'GERP++ rejected substitution score (conservation)',
    phastcons100way             DECIMAL(6,4)                         COMMENT 'PhastCons 100-way conservation score',
    phylop100way                DECIMAL(8,4)                         COMMENT 'PhyloP 100-way conservation p-value',
    gnomad_af                   DECIMAL(12,10)                       COMMENT 'gnomAD overall allele frequency',
    gnomad_af_eas               DECIMAL(12,10)                       COMMENT 'gnomAD East Asian allele frequency',
    gnomad_af_eur               DECIMAL(12,10)                       COMMENT 'gnomAD European (non-Finnish) allele frequency',
    gnomad_af_amr               DECIMAL(12,10)                       COMMENT 'gnomAD Admixed American allele frequency',
    gnomad_af_afr               DECIMAL(12,10)                       COMMENT 'gnomAD African/African-American allele frequency',
    gnomad_af_sas               DECIMAL(12,10)                       COMMENT 'gnomAD South Asian allele frequency',
    thousand_genomes_af         DECIMAL(12,10)                       COMMENT '1000 Genomes global allele frequency',
    exac_af                     DECIMAL(12,10)                       COMMENT 'ExAC allele frequency',
    clinvar_id                  VARCHAR(32)                          COMMENT 'ClinVar variation ID (VCV...)',
    clinvar_significance        VARCHAR(128)                         COMMENT 'ClinVar clinical significance: Pathogenic,Likely_pathogenic,Uncertain_significance,Likely_benign,Benign,Conflicting',
    clinvar_review_status       VARCHAR(64)                          COMMENT 'ClinVar review status: practice_guideline,reviewed_by_expert_panel,multiple_submitters,single_submitter',
    clinvar_phenotype           VARCHAR(512)                         COMMENT 'ClinVar associated phenotype/disease names',
    cosmic_id                   VARCHAR(32)                          COMMENT 'COSMIC mutation ID',
    cosmic_occurrence           INT                                  COMMENT 'COSMIC occurrence count in tumours',
    dbsnp_validation            VARCHAR(32)                          COMMENT 'dbSNP validation status',
    pubmed_ids                  VARCHAR(1024)                        COMMENT 'Comma-separated PubMed IDs referencing this variant',
    phenotype_association       VARCHAR(255)                         COMMENT 'Known phenotype association from curated databases',
    is_in_ad_gene               TINYINT(1)      DEFAULT 0            COMMENT 'In known Alzheimer disease gene: APP,PSEN1,PSEN2,APOE,TREM2,SORL1,ABCA7',
    is_in_pd_gene               TINYINT(1)      DEFAULT 0            COMMENT 'In known Parkinson disease gene: SNCA,LRRK2,PARK7,PINK1,PRKN,GBA',
    is_in_psych_gene            TINYINT(1)      DEFAULT 0            COMMENT 'In known psychiatric gene: BDNF,COMT,DISC1,DTNBP1,CACNA1C,NRG1,DRD2,HTR2A',
    custom_annotation           JSON                                 COMMENT 'Project-specific annotations as JSON',
    is_flagged                  TINYINT(1)      DEFAULT 0            COMMENT 'Flagged for clinical review',
    is_deleted                  TINYINT(1)      DEFAULT 0            COMMENT 'Soft-delete marker',
    notes                       TEXT                                 COMMENT 'Free-text remarks',
    created_at                  DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Record creation timestamp',
    updated_at                  DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Record last update timestamp',
    PRIMARY KEY (id),
    INDEX idx_sample_id                    (sample_id),
    INDEX idx_subject_id                   (subject_id),
    INDEX idx_chrom_pos                    (chromosome, position),
    INDEX idx_rs_id                        (rs_id),
    INDEX idx_variant_type                 (variant_type),
    INDEX idx_gene_symbol                  (gene_symbol),
    INDEX idx_gene_id                      (gene_id),
    INDEX idx_consequence                  (consequence),
    INDEX idx_impact                       (impact),
    INDEX idx_clinvar_significance         (clinvar_significance),
    INDEX idx_filter_status                (filter_status),
    INDEX idx_is_in_ad_gene                (is_in_ad_gene),
    INDEX idx_is_in_pd_gene                (is_in_pd_gene),
    INDEX idx_is_in_psych_gene             (is_in_psych_gene),
    INDEX idx_is_deleted                   (is_deleted),
    INDEX idx_sample_chrom_pos             (sample_id, chromosome, position),
    INDEX idx_gene_consequence             (gene_symbol, consequence),
    INDEX idx_clinvar_pathogenic           (clinvar_significance, gene_symbol),
    CONSTRAINT fk_genetic_variant_sample   FOREIGN KEY (sample_id)   REFERENCES genetic_sample(id)  ON DELETE CASCADE   ON UPDATE CASCADE,
    CONSTRAINT fk_genetic_variant_subject  FOREIGN KEY (subject_id)  REFERENCES subject(id)         ON DELETE RESTRICT  ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='Genetic variant records — individual variant calls from VCF with comprehensive functional annotations';


-- ============================================
-- 3. genetic_variant_annotation — extended annotation per-variant
-- ============================================
CREATE TABLE IF NOT EXISTS genetic_variant_annotation (
    id                          BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
    variant_id                  BIGINT UNSIGNED NOT NULL             COMMENT 'FK → genetic_variant.id',
    annotation_source           VARCHAR(64)     NOT NULL             COMMENT 'Source database/tool: VEP,Annovar,SnpEff,ClinVar,gnomAD,CADD,REVEL',
    annotation_version          VARCHAR(32)                          COMMENT 'Version of the annotation source',
    annotation_key              VARCHAR(128)    NOT NULL             COMMENT 'Annotation key name',
    annotation_value            TEXT                                 COMMENT 'Annotation value (text/JSON)',
    annotation_score            DECIMAL(20,10)                       COMMENT 'Numeric score if applicable',
    created_at                  DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Record creation timestamp',
    updated_at                  DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Record last update timestamp',
    PRIMARY KEY (id),
    INDEX idx_variant_id                   (variant_id),
    INDEX idx_annotation_source            (annotation_source),
    INDEX idx_annotation_key               (annotation_key),
    INDEX idx_variant_source               (variant_id, annotation_source),
    CONSTRAINT fk_varann_variant           FOREIGN KEY (variant_id)  REFERENCES genetic_variant(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='Extended per-variant annotations from bioinformatic tools and public databases';


-- ============================================
-- 4. genetic_polygenic_score — polygenic risk scores
-- ============================================
CREATE TABLE IF NOT EXISTS genetic_polygenic_score (
    id                          BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
    sample_id                   BIGINT UNSIGNED NOT NULL             COMMENT 'FK → genetic_sample.id',
    subject_id                  BIGINT UNSIGNED NOT NULL             COMMENT 'FK → subject.id',
    score_name                  VARCHAR(128)    NOT NULL             COMMENT 'PRS name: PRS_AD,PGRS_PD,PRS_SCZ,PRS_MDD,PRS_BD,PRS_HEIGHT etc.',
    score_value                 DECIMAL(18,12)  NOT NULL             COMMENT 'Raw polygenic score value',
    score_z                     DECIMAL(10,6)                        COMMENT 'Z-score normalised polygenic risk score',
    score_percentile            DECIMAL(7,4)                         COMMENT 'Percentile rank within reference population',
    reference_population        VARCHAR(64)                          COMMENT 'Reference population: EUR,EAS,AFR,AMR,SAS',
    reference_cohort            VARCHAR(128)                         COMMENT 'Reference cohort name (e.g. UK_Biobank,FinnGen,ADGC)',
    snp_count                   INT UNSIGNED                         COMMENT 'Number of SNPs used in calculation',
    calculation_method          VARCHAR(64)                          COMMENT 'Method: clumping_thresholding,ldpred2,prs_cs,SBayesR,lassosum',
    software_name               VARCHAR(64)                          COMMENT 'Software: PLINK,PRSice,ldpred2,PRS-CS,BIGSNAP',
    software_version            VARCHAR(32)                          COMMENT 'Software version',
    parameters                  JSON                                 COMMENT 'Calculation parameters as JSON',
    is_deleted                  TINYINT(1)      DEFAULT 0            COMMENT 'Soft-delete marker',
    created_at                  DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Record creation timestamp',
    updated_at                  DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Record last update timestamp',
    PRIMARY KEY (id),
    INDEX idx_sample_id                    (sample_id),
    INDEX idx_subject_id                   (subject_id),
    INDEX idx_score_name                   (score_name),
    INDEX idx_score_z                      (score_z),
    INDEX idx_score_percentile             (score_percentile),
    INDEX idx_subject_score                (subject_id, score_name),
    CONSTRAINT fk_prs_sample               FOREIGN KEY (sample_id)   REFERENCES genetic_sample(id)  ON DELETE CASCADE   ON UPDATE CASCADE,
    CONSTRAINT fk_prs_subject              FOREIGN KEY (subject_id)  REFERENCES subject(id)         ON DELETE RESTRICT  ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='Polygenic risk scores for psychiatric and neurodegenerative conditions';


-- ============================================
-- 5. genetic_sample_qc — per-sample QC metrics
-- ============================================
CREATE TABLE IF NOT EXISTS genetic_sample_qc (
    id                          BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
    sample_id                   BIGINT UNSIGNED NOT NULL             COMMENT 'FK → genetic_sample.id',
    qc_date                     DATETIME                             COMMENT 'Date/time QC was performed',
    qc_pipeline                 VARCHAR(64)                          COMMENT 'QC pipeline: FastQC,MultiQC,GATK_CollectSequencingArtifactMetrics,Picard',
    total_reads                 BIGINT UNSIGNED                      COMMENT 'Total number of reads (raw)',
    reads_after_filtering       BIGINT UNSIGNED                      COMMENT 'Reads remaining after QC filtering',
    pct_reads_retained          DECIMAL(5,2)                         COMMENT 'Percentage of reads retained after filtering',
    pct_q30                     DECIMAL(5,2)                         COMMENT 'Percentage of bases with quality >= Q30',
    mean_quality_score          DECIMAL(5,2)                         COMMENT 'Mean per-base quality score',
    gc_content_pct              DECIMAL(5,2)                         COMMENT 'GC content percentage',
    pct_duplicates              DECIMAL(5,2)                         COMMENT 'Percentage of duplicate reads',
    pct_adapter                 DECIMAL(5,2)                         COMMENT 'Percentage of adapter sequences detected',
    mean_read_length            DECIMAL(7,2)                         COMMENT 'Mean read length after trimming',
    insert_size_median          DECIMAL(10,2)                        COMMENT 'Median insert size (paired-end libraries)',
    insert_size_stddev          DECIMAL(10,2)                        COMMENT 'Standard deviation of insert size',
    pct_mapped                  DECIMAL(5,2)                         COMMENT 'Percentage of reads mapped to reference',
    pct_properly_paired         DECIMAL(5,2)                         COMMENT 'Percentage of properly paired reads',
    pct_chimera                 DECIMAL(5,2)                         COMMENT 'Percentage of chimeric reads',
    coverage_mean               DECIMAL(10,2)                        COMMENT 'Mean coverage depth across genome/targets',
    coverage_median             DECIMAL(10,2)                        COMMENT 'Median coverage depth',
    coverage_stddev             DECIMAL(10,2)                        COMMENT 'Standard deviation of coverage',
    coverage_1x_pct             DECIMAL(5,2)                         COMMENT 'Percentage of target bases covered >=1x',
    coverage_10x_pct            DECIMAL(5,2)                         COMMENT 'Percentage of target bases covered >=10x',
    coverage_20x_pct            DECIMAL(5,2)                         COMMENT 'Percentage of target bases covered >=20x',
    coverage_30x_pct            DECIMAL(5,2)                         COMMENT 'Percentage of target bases covered >=30x',
    coverage_50x_pct            DECIMAL(5,2)                         COMMENT 'Percentage of target bases covered >=50x',
    coverage_uniformity         DECIMAL(5,2)                         COMMENT 'Coverage uniformity (pct bases within 2x of mean)',
    het_snp_sensitivity         DECIMAL(6,4)                        COMMENT 'Heterozygous SNP sensitivity from known sites',
    het_snp_precision           DECIMAL(6,4)                        COMMENT 'Heterozygous SNP precision from known sites',
    hom_snp_sensitivity         DECIMAL(6,4)                        COMMENT 'Homozygous SNP sensitivity',
    indel_sensitivity           DECIMAL(6,4)                        COMMENT 'INDEL sensitivity',
    indel_precision             DECIMAL(6,4)                        COMMENT 'INDEL precision',
    ti_tv_ratio                 DECIMAL(5,3)                         COMMENT 'Transition/Transversion ratio for known SNPs',
    het_hom_ratio               DECIMAL(7,3)                         COMMENT 'Heterozygous/Homozygous ratio',
    dbSNP_concordance           DECIMAL(6,4)                        COMMENT 'Concordance with dbSNP known sites',
    sex_match                   VARCHAR(16)                          COMMENT 'Genetic vs reported sex: MATCH,MISMATCH,UNKNOWN',
    contamination_estimate      DECIMAL(7,4)                        COMMENT 'Estimated sample contamination fraction',
    ethnicity_prediction        VARCHAR(32)                          COMMENT 'Predicted ethnicity from genotype: EUR,EAS,AFR,AMR,SAS',
    relatedness_check           VARCHAR(64)                          COMMENT 'Relatedness check: SELF,UNRELATED,PARENT,CHILD,SIBLING',
    identity_check              VARCHAR(64)                          COMMENT 'Identity check vs expected: MATCH,MISMATCH,CONTAMINATION',
    overall_qc_status           VARCHAR(16)     NOT NULL DEFAULT 'PENDING' COMMENT 'Overall QC verdict: PENDING,PASS,WARN,FAIL',
    qc_report_path              VARCHAR(512)                         COMMENT 'MinIO path to full QC report',
    qc_metrics_json             JSON                                 COMMENT 'Complete QC metrics as JSON blob',
    is_deleted                  TINYINT(1)      DEFAULT 0            COMMENT 'Soft-delete marker',
    created_at                  DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Record creation timestamp',
    updated_at                  DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Record last update timestamp',
    PRIMARY KEY (id),
    INDEX idx_sample_id                    (sample_id),
    INDEX idx_qc_date                      (qc_date),
    INDEX idx_overall_qc_status            (overall_qc_status),
    INDEX idx_coverage_mean                (coverage_mean),
    INDEX idx_sample_qc_status             (sample_id, overall_qc_status),
    CONSTRAINT fk_sample_qc_sample         FOREIGN KEY (sample_id)   REFERENCES genetic_sample(id)  ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='Per-sample sequencing and genotyping quality control metrics';
